version: '3.7'

services:
  web:
    build: ./
    command: python run.py
    volumes: 
      - ./:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on: 
      - db
  
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=podera01
      - POSTGRES_PASSWORD=isobar2021
      - POSTGRES_DB=streetview

volumes:
  postgres_data: