"""empty message

Revision ID: 4751837119af
Revises: 
Create Date: 2021-06-08 15:39:03.928059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4751837119af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_auth_id'), 'auth', ['id'], unique=True)
    op.create_table('player',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=True)
    op.create_table('treasure',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('tag_line_1', sa.String(length=100), nullable=True),
    sa.Column('tag_line_2', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_treasure_id'), 'treasure', ['id'], unique=True)
    op.create_table('clue',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('treasure_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Boolean(), nullable=False),
    sa.Column('startpoint', sa.Boolean(), nullable=False),
    sa.Column('slug', postgresql.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('marker_pos', sa.String(length=150), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_bonus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['treasure_id'], ['treasure.id'], onupdate='Cascade', ondelete='Cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clue_id'), 'clue', ['id'], unique=True)
    op.create_table('player_leaderboard',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('treasure_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('player_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], onupdate='Cascade', ondelete='Cascade'),
    sa.ForeignKeyConstraint(['treasure_id'], ['treasure.id'], onupdate='Cascade', ondelete='Cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_leaderboard_id'), 'player_leaderboard', ['id'], unique=True)
    op.create_table('clue_options',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('clue_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('coordinates', sa.String(length=500), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clue_id'], ['clue.id'], onupdate='Cascade', ondelete='Cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clue_options_id'), 'clue_options', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clue_options_id'), table_name='clue_options')
    op.drop_table('clue_options')
    op.drop_index(op.f('ix_player_leaderboard_id'), table_name='player_leaderboard')
    op.drop_table('player_leaderboard')
    op.drop_index(op.f('ix_clue_id'), table_name='clue')
    op.drop_table('clue')
    op.drop_index(op.f('ix_treasure_id'), table_name='treasure')
    op.drop_table('treasure')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_auth_id'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
