"""empty message

Revision ID: 751c2f4f59e8
Revises: 
Create Date: 2021-04-02 07:56:21.260083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '751c2f4f59e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clue', sa.Column('is_bonus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

