"""empty message

Revision ID: 86ea1338caa3
Revises: 
Create Date: 2020-12-07 11:07:52.264292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ea1338caa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treasure', sa.Column('objective', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treasure', 'objective')
    # ### end Alembic commands ###
